// Fully filled fake profiles for seed-full.mjs. Every account is tagged
// app_metadata = { seed: 'fake', batch: 'full-<timestamp>' } and removed by delete.mjs.
// Copy rules: plain ASCII punctuation, no em/en dashes.

export const CITIES = {
  KL: { city: 'Kuala Lumpur', lat: 3.139, lng: 101.687 },
  PJ: { city: 'Petaling Jaya', lat: 3.107, lng: 101.607 },
  SA: { city: 'Shah Alam', lat: 3.073, lng: 101.518 },
  SJ: { city: 'Subang Jaya', lat: 3.05, lng: 101.585 },
  CJ: { city: 'Cyberjaya', lat: 2.922, lng: 101.655 },
  PG: { city: 'George Town', lat: 5.414, lng: 100.329 },
  JB: { city: 'Johor Bahru', lat: 1.492, lng: 103.741 },
  IP: { city: 'Ipoh', lat: 4.597, lng: 101.09 },
  MK: { city: 'Melaka', lat: 2.189, lng: 102.25 },
  KK: { city: 'Kota Kinabalu', lat: 5.98, lng: 116.073 },
  KC: { city: 'Kuching', lat: 1.553, lng: 110.359 },
}

// Short keys keep the table readable:
// n name, u username, g gender, a age, c city key, job, edu, h height_cm, rel religion,
// lang languages, dr drinking, sm smoking, pets, kids children, goal relationship_goal,
// bio, tags (tag slugs), pr prompts [[prompt_key, answer], x3].
export const PEOPLE_FULL = [
  // Women
  {
    n: 'Nurul Izzah', u: 'nurul.izzah', g: 'female', a: 26, c: 'KL', job: 'Data analyst at a fintech',
    edu: 'bachelor', h: 158, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'want', goal: 'serious',
    bio: 'Spreadsheets by day, K-drama by night. I make a very good sambal and I will not share the recipe until the third date.',
    tags: ['coffee', 'kdramas', 'hiking', 'mamak', 'photography', 'baking'],
    pr: [
      ['mamak_order', 'Roti telur bawang, teh o ais limau. Every single time, the waiter knows me already.'],
      ['ideal_weekend', 'Sunrise hike at Bukit Tabur, nap, then a long dinner with friends in Kampung Baru.'],
      ['green_flags', 'You text back when you said you would. You are nice to the cat. That is the whole list.'],
    ],
  },
  {
    n: 'Tan Hui Min', u: 'huimin.tan', g: 'female', a: 29, c: 'PG', job: 'Hospital pharmacist',
    edu: 'bachelor', h: 162, rel: 'buddhism', lang: ['mandarin', 'hokkien', 'english', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'Born and raised in George Town. I know which char kway teow stall is worth the queue and which one is just famous on Instagram.',
    tags: ['cooking', 'cycling', 'matcha', 'travel', 'plants', 'cdramas'],
    pr: [
      ['way_to_heart', 'Bring me the last plate of apom balik before the stall closes. Bonus points if you queued in the rain.'],
      ['lets_debate', 'Penang laksa is better than every other laksa. I am ready, bring your arguments.'],
      ['simple_pleasures', 'Cycling along the Esplanade at 7am before it gets hot, then kopi C at the corner shop.'],
    ],
  },
  {
    n: 'Kavya Raman', u: 'kavya.draws', g: 'female', a: 24, c: 'PJ', job: 'Junior architect',
    edu: 'bachelor', h: 160, rel: 'hinduism', lang: ['tamil', 'english', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'not_sure', goal: 'long_term_open',
    bio: 'I draw buildings for a living and doodle people in cafes for fun. If you see me sketching you, I promise it is a compliment.',
    tags: ['drawing', 'dancing', 'bollywood', 'coffee', 'staycations', 'dogs'],
    pr: [
      ['weirdly_good_at', 'Guessing the year a shophouse was built just by looking at the windows.'],
      ['karaoke_song', 'Anything by A.R. Rahman. I will do the high notes badly but with full confidence.'],
      ['perfect_first_date', 'Walk around Jalan Sultan, look at old buildings, then thosai and filter coffee.'],
    ],
  },
  {
    n: 'Sharifah Aleeya', u: 'aleeya.s', g: 'female', a: 31, c: 'SA', job: 'HR manager',
    edu: 'master', h: 165, rel: 'islam', lang: ['malay', 'english', 'arabic'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'want', goal: 'serious',
    bio: 'I interview people for a living, so please do not be nervous. I swim twice a week and bake banana cake on Sundays.',
    tags: ['baking', 'swimming', 'books', 'volunteering', 'meditation'],
    pr: [
      ['looking_for', 'Someone kind, a bit funny and serious about building a life together. Family matters to me.'],
      ['simple_pleasures', 'Fresh banana cake out of the oven and a quiet Sunday with a good book.'],
      ['two_truths_lie', 'I have read 40 books this year. I once met Siti Nurhaliza. I can not ride a bicycle.'],
    ],
  },
  {
    n: 'Grace Lim', u: 'grace.flies', g: 'female', a: 27, c: 'SJ', job: 'Flight attendant',
    edu: 'diploma', h: 168, rel: 'christianity', lang: ['english', 'mandarin', 'cantonese', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'long_term_open',
    bio: 'Half my week is in the air, the other half is in yoga class or in Subang trying new brunch places.',
    tags: ['travel', 'backpacking', 'skincare', 'yoga', 'beach', 'photography'],
    pr: [
      ['travel_story', 'Got stuck in Osaka for two extra days because of a typhoon. Best accidental holiday of my life.'],
      ['ideal_weekend', 'Yoga in the morning, brunch in SS15, and a movie on the couch with zero alarms.'],
      ['green_flags', 'You are fine with me being away a few days a week and you send me food recommendations for every city.'],
    ],
  },
  {
    n: 'Melissa Gimbang', u: 'melissa.dives', g: 'female', a: 25, c: 'KK', job: 'Dive instructor',
    edu: 'diploma', h: 157, rel: 'christianity', lang: ['malay', 'english', 'other'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'want', goal: 'serious',
    bio: 'Kadazan girl from Penampang. I spend more time underwater than on land. Tamu on Sunday, sunset at Tanjung Aru after.',
    tags: ['diving', 'beach', 'hiking', 'camping', 'karaoke', 'dogs'],
    pr: [
      ['weirdly_good_at', 'Spotting a turtle from 20 metres away. Also very good at hinava.'],
      ['perfect_first_date', 'Island hopping to Manukan, snorkelling, then grilled fish at the night market.'],
      ['karaoke_song', 'Sumandak Kampung, and everyone in the room has to sing along.'],
    ],
  },
  {
    n: 'Dayang Nur Ain', u: 'dayang.ain', g: 'female', a: 23, c: 'KC', job: 'Staff nurse',
    edu: 'diploma', h: 155, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'want', goal: 'serious',
    bio: 'Nurse working shifts, so I appreciate someone patient. My cats are called Laksa and Kolo and they are in charge.',
    tags: ['cats', 'baking', 'kdramas', 'karaoke', 'volunteering'],
    pr: [
      ['mamak_order', 'Mee goreng basah and a cold Milo dinosaur after a night shift.'],
      ['way_to_heart', 'Bring Sarawak laksa to the hospital at 3am. I will remember it forever.'],
      ['lets_debate', 'Kek lapis is the best souvenir in Malaysia. Do not even try.'],
    ],
  },
  {
    n: 'Ong Pei Shan', u: 'peishan.ong', g: 'female', a: 22, c: 'IP', job: 'Accounting student and part-time tutor',
    edu: 'bachelor', h: 159, rel: 'taoism', lang: ['cantonese', 'mandarin', 'english', 'malay'], dr: 'never', sm: 'never',
    pets: 'none', kids: 'not_sure', goal: 'not_sure',
    bio: 'Ipoh girl, final year. I know every cafe in Old Town and I will judge your white coffee order.',
    tags: ['matcha', 'coffee', 'thrifting', 'kpop', 'drawing', 'photography'],
    pr: [
      ['simple_pleasures', 'Tauge chicken on a rainy day, then an hour of thrifting with no plan.'],
      ['two_truths_lie', 'I have been to 6 BTS concerts. I can draw with both hands. I have never tried durian.'],
      ['ideal_weekend', 'Cafe hopping in Old Town, sketching the murals, then dim sum with my grandma.'],
    ],
  },
  {
    n: 'Aishwarya Pillai', u: 'aish.pillai', g: 'female', a: 30, c: 'CJ', job: 'Cloud engineer',
    edu: 'master', h: 163, rel: 'hinduism', lang: ['tamil', 'english', 'malay', 'hindi'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'I keep servers alive for a living and my plants alive as a hobby. 5K runner, podcast addict, decent cook.',
    tags: ['coding', 'ai', 'running', 'podcasts', 'cooking', 'plants'],
    pr: [
      ['looking_for', 'A partner who is curious, a little nerdy and up for a run around the lake on Saturday morning.'],
      ['weirdly_good_at', 'Making restaurant level rasam with whatever is left in the fridge.'],
      ['lets_debate', 'Pineapple on pizza is fine. Pineapple in fried rice is even better.'],
    ],
  },
  {
    n: 'Nur Syafiqah', u: 'syafiqah.reads', g: 'female', a: 28, c: 'JB', job: 'Primary school teacher',
    edu: 'bachelor', h: 156, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'want', goal: 'serious',
    bio: 'Teaching 10 year olds means I can handle anything. Bookworm, writer of unfinished novels, mee rebus enthusiast.',
    tags: ['books', 'writing', 'cats', 'mamak', 'staycations'],
    pr: [
      ['perfect_first_date', 'A bookstore in Mid Valley Southkey, each of us picks a book for the other, then coffee.'],
      ['green_flags', 'You read, even if it is only comics. You say thank you to the cleaner.'],
      ['travel_story', 'Took the overnight train to Kelantan alone and ended up adopted by a family for Raya.'],
    ],
  },
  {
    n: 'Jasmine Ng', u: 'jasmine.ng', g: 'female', a: 33, c: 'KL', job: 'Marketing director',
    edu: 'master', h: 166, rel: 'none', lang: ['english', 'cantonese', 'mandarin'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'not_sure', goal: 'long_term_open',
    bio: 'Busy job, busier dog. I play pickleball like it is the Olympics and I will always pick the restaurant.',
    tags: ['concerts', 'pickleball', 'investing', 'travel', 'fashion', 'dogs'],
    pr: [
      ['two_truths_lie', 'I ran a half marathon in Seoul. I have a corgi named Dumpling. I have never been late to a meeting.'],
      ['ideal_weekend', 'Pickleball at 8, brunch in Bangsar, and a long walk with the dog at the park.'],
      ['looking_for', 'Someone ambitious who still knows how to switch off. Good conversation is non-negotiable.'],
    ],
  },
  {
    n: 'Elena Petrova', u: 'elena.in.kl', g: 'female', a: 29, c: 'KL', job: 'UX researcher',
    edu: 'master', h: 170, rel: 'christianity', lang: ['russian', 'english', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'cat', kids: 'not_sure', goal: 'serious',
    bio: 'From Kazan, in KL for two years now. Learning Malay one menu at a time. Bouldering on weekdays, hiking on weekends.',
    tags: ['languages', 'bouldering', 'coffee', 'art', 'hiking'],
    pr: [
      ['travel_story', 'Took a wrong bus in Cameron Highlands and ended up helping a family pick tea for an afternoon.'],
      ['weirdly_good_at', 'Ordering in Malay without the waiter switching to English. Sometimes.'],
      ['way_to_heart', 'Teach me a new Malay word every day and take me to your favourite nasi lemak stall.'],
    ],
  },
  {
    n: 'Hannah Joseph', u: 'hannah.physio', g: 'female', a: 26, c: 'PG', job: 'Physiotherapist',
    edu: 'bachelor', h: 161, rel: 'christianity', lang: ['english', 'malay', 'other'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'I fix knees and backs. Malayali family, Penang heart. Will happily correct your posture on our date.',
    tags: ['fitness', 'running', 'swimming', 'cooking', 'podcasts'],
    pr: [
      ['simple_pleasures', 'A swim at Batu Ferringhi at sunset and appam with my mum after.'],
      ['green_flags', 'You stretch after running. You call your mother.'],
      ['perfect_first_date', 'Climb Penang Hill on foot, take the funicular down, then nasi kandar.'],
    ],
  },
  {
    n: 'Farhana Ismail', u: 'farhana.art', g: 'female', a: 21, c: 'SA', job: 'Graphic design student',
    edu: 'diploma', h: 154, rel: 'islam', lang: ['malay', 'english', 'korean'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'not_sure', goal: 'not_sure',
    bio: 'Design student at UiTM. I draw fan art, cosplay sometimes and I can talk about K-pop for hours.',
    tags: ['kpop', 'drawing', 'cosplay', 'anime', 'matcha'],
    pr: [
      ['karaoke_song', 'Super Shy by NewJeans. Choreography included, no shame at all.'],
      ['weirdly_good_at', 'Drawing anyone as an anime character in under five minutes.'],
      ['ideal_weekend', 'Comic Fiesta if it is on. If not, matcha latte and drawing at a cafe in Seksyen 7.'],
    ],
  },
  {
    n: 'Chong Li Wen', u: 'liwen.bakes', g: 'female', a: 35, c: 'MK', job: 'Cafe owner',
    edu: 'diploma', h: 160, rel: 'buddhism', lang: ['hokkien', 'mandarin', 'english', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'both', kids: 'have', goal: 'serious',
    bio: 'I run a small cafe near Jonker Street. Mum of one amazing 8 year old. Looking for something real and calm.',
    tags: ['baking', 'coffee', 'plants', 'cooking', 'dogs', 'cats'],
    pr: [
      ['looking_for', 'Someone steady and warm who is fine with a busy single mum and a very loud dog.'],
      ['way_to_heart', 'Help me close the cafe on a Sunday night and stay for the leftover cake.'],
      ['simple_pleasures', 'Cendol by the river after the weekend crowd goes home.'],
    ],
  },
  {
    n: 'Puteri Balqis', u: 'balqis.qa', g: 'female', a: 24, c: 'CJ', job: 'QA engineer',
    edu: 'bachelor', h: 162, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'I find bugs for a living, so yes, I will find the bug in your argument. Gamer, badminton player, nasi lemak loyalist.',
    tags: ['gaming', 'esports', 'tech', 'mamak', 'badminton'],
    pr: [
      ['lets_debate', 'Mobile Legends is harder than Valorant. Fight me in the comments.'],
      ['mamak_order', 'Maggi goreng double telur and teh tarik kurang manis.'],
      ['two_truths_lie', 'I was a state level badminton player. I have 3 gaming chairs. I hate durian.'],
    ],
  },
  {
    n: 'Sarah Tiong', u: 'sarah.tiong', g: 'female', a: 27, c: 'KC', job: 'Corporate lawyer',
    edu: 'bachelor', h: 158, rel: 'christianity', lang: ['mandarin', 'english', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'want', goal: 'serious',
    bio: 'Foochow from Sibu, working in Kuching. I read contracts all week, so on weekends I want documentaries and kampua mee.',
    tags: ['books', 'pickleball', 'durian', 'travel', 'documentaries'],
    pr: [
      ['lets_debate', 'Kampua is better than kolo mee. As a lawyer I can argue this for 3 hours.'],
      ['perfect_first_date', 'Walk along the Waterfront, a boat ride across the river, then dinner at Carpenter Street.'],
      ['green_flags', 'You have opinions but you also listen.'],
    ],
  },
  {
    n: 'Jessica Jimbun', u: 'jessica.jimbun', g: 'female', a: 30, c: 'KC', job: 'Event planner',
    edu: 'diploma', h: 163, rel: 'christianity', lang: ['malay', 'english', 'other'], dr: 'often', sm: 'sometimes',
    pets: 'none', kids: 'not_sure', goal: 'long_term_open',
    bio: 'Iban girl who plans everyone else\'s parties. Rainforest World Music Festival is my Christmas.',
    tags: ['edm', 'concerts', 'dancing', 'karaoke', 'beach', 'fashion'],
    pr: [
      ['ideal_weekend', 'Gawai at the longhouse with the whole family, or a beach day at Damai if work lets me.'],
      ['karaoke_song', 'Dancing Queen. The whole room dances, that is the rule.'],
      ['two_truths_lie', 'I organised a wedding for 2000 guests. I can cook ayam pansuh. I am scared of the sea.'],
    ],
  },
  {
    n: 'Mira Hassan', u: 'mira.interiors', g: 'female', a: 37, c: 'PJ', job: 'Interior designer',
    edu: 'bachelor', h: 164, rel: 'islam', lang: ['malay', 'english', 'arabic'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'have', goal: 'serious',
    bio: 'Mother of two teenagers, designer of calm living rooms. I paint on Friday nights and I take my coffee black.',
    tags: ['art', 'painting', 'plants', 'staycations', 'meditation'],
    pr: [
      ['looking_for', 'A grown up, honest man who enjoys quiet evenings and is good with teenagers.'],
      ['simple_pleasures', 'Rearranging a room until the light falls just right.'],
      ['travel_story', 'Got lost in the souks of Fez and found the best carpet shop of my life.'],
    ],
  },
  // Men
  {
    n: 'Amir Hamzah', u: 'amir.codes', g: 'male', a: 28, c: 'KL', job: 'Software engineer',
    edu: 'bachelor', h: 175, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'want', goal: 'serious',
    bio: 'Backend developer, futsal every Wednesday, mamak every night after. I have a cat named Bug, which is ironic.',
    tags: ['coding', 'futsal', 'mamak', 'gaming', 'gadgets'],
    pr: [
      ['mamak_order', 'Roti canai kosong, kuah campur, and a teh o ais. Simple man.'],
      ['weirdly_good_at', 'Fixing every relative\'s WiFi during Raya.'],
      ['looking_for', 'Someone I can talk to for hours at the mamak and who laughs at my bad jokes.'],
    ],
  },
  {
    n: 'Lim Wei Jie', u: 'weijie.lim', g: 'male', a: 30, c: 'PJ', job: 'Product designer',
    edu: 'bachelor', h: 172, rel: 'none', lang: ['english', 'mandarin', 'cantonese', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'long_term_open',
    bio: 'I design apps and take film photos. Weekend cyclist, weekday matcha drinker, thrift store regular.',
    tags: ['art', 'photography', 'cycling', 'coffee', 'matcha', 'thrifting'],
    pr: [
      ['ideal_weekend', 'Morning ride to Putrajaya, film photos at the lake, then pan mee in SS2.'],
      ['two_truths_lie', 'I own 9 film cameras. I have cycled from KL to Melaka. I can not swim.'],
      ['green_flags', 'You have a favourite font. Bonus if it is not Comic Sans.'],
    ],
  },
  {
    n: 'Vikram Nair', u: 'vikram.nair', g: 'male', a: 32, c: 'CJ', job: 'Data scientist',
    edu: 'master', h: 178, rel: 'hinduism', lang: ['english', 'malay', 'tamil', 'hindi'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'want', goal: 'serious',
    bio: 'I build models that predict things, except my own love life. Runner, home cook, golden retriever dad.',
    tags: ['ai', 'investing', 'running', 'bollywood', 'cooking', 'podcasts'],
    pr: [
      ['way_to_heart', 'Run 10K with me and then let me cook you the best chicken biryani in Cyberjaya.'],
      ['lets_debate', 'Shah Rukh Khan movies are a valid personality trait.'],
      ['perfect_first_date', 'Sunrise run at Taman Tasik Cyberjaya, then breakfast. If you do not run, just breakfast.'],
    ],
  },
  {
    n: 'Faiz Iskandar', u: 'faiz.iskandar', g: 'male', a: 25, c: 'SA', job: 'Mechanical engineer',
    edu: 'bachelor', h: 170, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'Engineer at an automotive plant. Weekends are for fishing, football and fixing my old Civic.',
    tags: ['cars', 'football', 'fishing', 'camping', 'mamak'],
    pr: [
      ['simple_pleasures', 'Fishing at dawn at Tasik Shah Alam with a flask of kopi.'],
      ['two_truths_lie', 'I rebuilt an engine by myself. I support Liverpool. I have never been camping.'],
      ['looking_for', 'Someone down to earth who will come to my mum\'s house for Raya and survive the questions.'],
    ],
  },
  {
    n: 'Jason Teoh', u: 'jason.cooks', g: 'male', a: 27, c: 'PG', job: 'Sous chef',
    edu: 'diploma', h: 174, rel: 'buddhism', lang: ['hokkien', 'mandarin', 'english', 'malay'], dr: 'sometimes', sm: 'sometimes',
    pets: 'cat', kids: 'not_sure', goal: 'long_term_open',
    bio: 'Sous chef in George Town. I cook all day and still want to eat out at night. Cyclist when it is not raining.',
    tags: ['cooking', 'durian', 'cycling', 'edm', 'photography'],
    pr: [
      ['way_to_heart', 'Let me cook for you. If you clean up after, I might propose.'],
      ['lets_debate', 'Musang King is overrated. Black Thorn is the real king.'],
      ['ideal_weekend', 'Durian at Balik Pulau, ride back to town, nap, then a night out on Love Lane.'],
    ],
  },
  {
    n: 'Harith Zulkifli', u: 'harith.z', g: 'male', a: 23, c: 'SJ', job: 'Medical student',
    edu: 'bachelor', h: 177, rel: 'islam', lang: ['malay', 'english', 'arabic'], dr: 'never', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'Final year medical student. Swimmer, reader, occasional volunteer at a free clinic. Coffee keeps me alive.',
    tags: ['swimming', 'books', 'badminton', 'podcasts', 'volunteering'],
    pr: [
      ['two_truths_lie', 'I have delivered a baby. I can swim 5K. I fainted the first time I saw blood.'],
      ['green_flags', 'You are patient with my exam season. I promise I will make it up to you.'],
      ['simple_pleasures', 'A quiet library, a cold drink and one hour without my phone.'],
    ],
  },
  {
    n: 'Daniel Fernandez', u: 'daniel.melaka', g: 'male', a: 34, c: 'MK', job: 'Tour guide',
    edu: 'diploma', h: 176, rel: 'christianity', lang: ['english', 'malay', 'other'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'want', goal: 'serious',
    bio: 'Portuguese Eurasian from the Settlement in Melaka. I tell stories for a living and sing Kristang songs badly.',
    tags: ['travel', 'documentaries', 'fishing', 'music', 'karaoke', 'dogs'],
    pr: [
      ['weirdly_good_at', 'Telling you the history of any street in Melaka in under two minutes.'],
      ['perfect_first_date', 'Sunset at the Portuguese Settlement, grilled stingray, and a walk along the river.'],
      ['karaoke_song', 'Jinkli Nona, and you will learn the words by the end of the night.'],
    ],
  },
  {
    n: 'Gurpreet Singh', u: 'gurpreet.ipoh', g: 'male', a: 29, c: 'IP', job: 'Civil engineer',
    edu: 'bachelor', h: 182, rel: 'sikhism', lang: ['english', 'malay', 'hindi', 'other'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'Building bridges in Perak, literally. Gym five days a week, badminton on Sundays, my mum\'s parathas forever.',
    tags: ['hiking', 'badminton', 'gym', 'cooking', 'bollywood'],
    pr: [
      ['ideal_weekend', 'Hike up Bukit Kledang in the morning, then a long lunch at a kopitiam in Old Town.'],
      ['way_to_heart', 'Good food and honest conversation. And if you can beat me at badminton, I am yours.'],
      ['simple_pleasures', 'Hot chai while it rains in Ipoh in the afternoon.'],
    ],
  },
  {
    n: 'Hafiz Azlan', u: 'hafiz.azlan', g: 'male', a: 31, c: 'JB', job: 'Logistics manager',
    edu: 'bachelor', h: 173, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'sometimes',
    pets: 'cat', kids: 'want', goal: 'serious',
    bio: 'I move containers between JB and the rest of the world. Football on Tuesdays, fishing on Saturdays, mee bandung always.',
    tags: ['football', 'fishing', 'cars', 'mamak', 'staycations'],
    pr: [
      ['mamak_order', 'Mee bandung Muar and a cold Milo ais. Not a real mamak order but I stand by it.'],
      ['looking_for', 'Someone who wants to settle down and still go on road trips up the coast.'],
      ['travel_story', 'Drove from JB to Kota Bharu in one go just for nasi kerabu. Worth it.'],
    ],
  },
  {
    n: 'Kenneth Yong', u: 'kenneth.reef', g: 'male', a: 26, c: 'KK', job: 'Marine biologist',
    edu: 'master', h: 171, rel: 'christianity', lang: ['english', 'malay', 'mandarin'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'long_term_open',
    bio: 'I count fish and coral for a living. Half Kadazan, half Hakka, full Sabahan. Stargazing at Kundasang is my happy place.',
    tags: ['diving', 'beach', 'nature', 'stargazing', 'documentaries', 'hiking'],
    pr: [
      ['weirdly_good_at', 'Naming every fish you see on a snorkel trip, including the ugly ones.'],
      ['ideal_weekend', 'Drive up to Kundasang, look at stars, Sabah tea in the morning with a view of Kinabalu.'],
      ['green_flags', 'You do not touch the coral. You bring a reusable bottle.'],
    ],
  },
  {
    n: 'Ryan Jalong', u: 'ryan.jalong', g: 'male', a: 28, c: 'KC', job: 'Firefighter',
    edu: 'diploma', h: 180, rel: 'christianity', lang: ['malay', 'english', 'other'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'want', goal: 'serious',
    bio: 'Iban from Sri Aman, firefighter in Kuching. Gym, football, camping by the river. My dog Bujang approves all dates.',
    tags: ['gym', 'football', 'camping', 'karaoke', 'dogs'],
    pr: [
      ['two_truths_lie', 'I have rescued a cat from a tree. I can cook for 50 people. I am afraid of heights.'],
      ['way_to_heart', 'Kolo mee breakfast and a long drive to Bako on my day off.'],
      ['looking_for', 'Someone loyal, a bit adventurous and okay with my shift schedule.'],
    ],
  },
  {
    n: 'Hiroshi Tanaka', u: 'hiroshi.kl', g: 'male', a: 33, c: 'KL', job: 'Automotive engineer',
    edu: 'bachelor', h: 171, rel: 'none', lang: ['japanese', 'english', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'From Nagoya, living in KL for four years. I love Malaysian food more than ramen now, please do not tell my mother.',
    tags: ['cars', 'running', 'cooking', 'photography', 'languages'],
    pr: [
      ['lets_debate', 'Nasi lemak is the best breakfast in the world. Yes, better than Japanese breakfast.'],
      ['travel_story', 'Took a night bus to Kuala Terengganu and ate keropok lekor for three days straight.'],
      ['perfect_first_date', 'You show me your favourite local food spot, I will cook you proper Japanese curry next time.'],
    ],
  },
  {
    n: 'Marcus Ho', u: 'marcus.ho', g: 'male', a: 36, c: 'SJ', job: 'Airline pilot',
    edu: 'bachelor', h: 179, rel: 'christianity', lang: ['english', 'cantonese', 'mandarin'], dr: 'sometimes', sm: 'never',
    pets: 'dog', kids: 'want', goal: 'serious',
    bio: 'I fly A330s and come home to a beagle who thinks I am a stranger. Ready for something long term.',
    tags: ['travel', 'pickleball', 'investing', 'swimming', 'coffee'],
    pr: [
      ['travel_story', 'Saw the northern lights from the cockpit over Russia. Still my favourite night at work.'],
      ['green_flags', 'You are independent and also happy to pick me up from the airport sometimes.'],
      ['ideal_weekend', 'Pickleball, a long brunch, and walking the beagle around Subang lake.'],
    ],
  },
  {
    n: 'Arif Danial', u: 'arif.danial', g: 'male', a: 21, c: 'CJ', job: 'Computer science student',
    edu: 'bachelor', h: 168, rel: 'islam', lang: ['malay', 'english', 'japanese'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'not_sure', goal: 'not_sure',
    bio: 'CS student at MMU, learning Japanese so I can watch anime without subtitles. Mythic in Mobile Legends.',
    tags: ['anime', 'esports', 'gaming', 'coding', 'cosplay'],
    pr: [
      ['weirdly_good_at', 'Finishing a 24 episode anime in one weekend and still submitting my assignment.'],
      ['karaoke_song', 'Gurenge from Demon Slayer. I know every word.'],
      ['mamak_order', 'Nasi goreng pattaya and an iced Milo. Fuel for a night of coding.'],
    ],
  },
  {
    n: 'Suresh Kumar', u: 'suresh.kitchen', g: 'male', a: 38, c: 'KL', job: 'Restaurant owner',
    edu: 'secondary', h: 169, rel: 'hinduism', lang: ['tamil', 'malay', 'english'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'have', goal: 'serious',
    bio: 'I run a banana leaf restaurant in Brickfields. Single dad, proud of my daughter, believer in second chances.',
    tags: ['cooking', 'mamak', 'football', 'music', 'volunteering'],
    pr: [
      ['looking_for', 'A kind partner who loves family dinners and is not shy about second helpings.'],
      ['way_to_heart', 'Eat with your hands at my restaurant and tell me honestly if the fish curry needs more salt.'],
      ['simple_pleasures', 'Old Tamil songs on the radio while I prep the kitchen at 6am.'],
    ],
  },
  {
    n: 'Alex Chua', u: 'alex.brews', g: 'male', a: 22, c: 'IP', job: 'Barista',
    edu: 'diploma', h: 174, rel: 'none', lang: ['cantonese', 'english', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'cat', kids: 'not_sure', goal: 'casual',
    bio: 'Barista in Ipoh. I will draw a cat on your latte. I DJ small parties and thrift most of my clothes.',
    tags: ['coffee', 'edm', 'thrifting', 'drawing', 'cycling'],
    pr: [
      ['weirdly_good_at', 'Latte art. A swan, a cat, your initials, you name it.'],
      ['ideal_weekend', 'Morning shift, thrift shopping in the afternoon, a small gig at night.'],
      ['two_truths_lie', 'I have a vinyl collection of 300 records. I hate coffee. I was born in Taiping.'],
    ],
  },
  {
    n: 'Khairul Anwar', u: 'khairul.anwar', g: 'male', a: 35, c: 'MK', job: 'Civil servant',
    edu: 'bachelor', h: 172, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'cat', kids: 'want', goal: 'serious',
    bio: 'Government officer in Melaka. Simple man: badminton, fishing at Klebang and asam pedas on Fridays.',
    tags: ['badminton', 'fishing', 'hiking', 'mamak', 'durian'],
    pr: [
      ['looking_for', 'Someone sincere who wants to build a family and enjoys simple things.'],
      ['simple_pleasures', 'Coconut shake at Klebang beach as the sun goes down.'],
      ['perfect_first_date', 'Asam pedas lunch, then a slow walk along the Melaka River.'],
    ],
  },
  {
    n: 'Tom Becker', u: 'tom.becker', g: 'male', a: 31, c: 'PJ', job: 'Solar energy consultant',
    edu: 'master', h: 186, rel: 'none', lang: ['english', 'other', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'long_term_open',
    bio: 'German, in PJ for three years putting solar panels on factory roofs. Climber, hiker, very slow learner of Malay.',
    tags: ['bouldering', 'hiking', 'cycling', 'languages', 'beach'],
    pr: [
      ['lets_debate', 'Malaysian breakfast beats German breakfast. My family disagrees.'],
      ['two_truths_lie', 'I have climbed in Batu Caves. I speak four languages. I like durian.'],
      ['ideal_weekend', 'Bouldering session, hike at Bukit Gasing, and a big dinner at a Chinese seafood place.'],
    ],
  },
  {
    n: 'Ethan Goh', u: 'ethan.goh', g: 'male', a: 25, c: 'JB', job: 'Sales engineer',
    edu: 'bachelor', h: 176, rel: 'buddhism', lang: ['mandarin', 'english', 'hokkien', 'malay'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'I cross the Causeway every day for work, so I am very patient. Gym, cars and too many C-dramas.',
    tags: ['gym', 'investing', 'crypto', 'cars', 'cdramas'],
    pr: [
      ['simple_pleasures', 'Bak kut teh on Sunday morning with the family.'],
      ['travel_story', 'Missed my flight in Bangkok and made friends with a whole tour group from Ipoh.'],
      ['green_flags', 'You have a plan for the future, even if it changes every week.'],
    ],
  },
  {
    n: 'Nazrin Hakimi', u: 'nazrin.films', g: 'male', a: 27, c: 'KL', job: 'Video producer',
    edu: 'bachelor', h: 174, rel: 'islam', lang: ['malay', 'english'], dr: 'never', sm: 'never',
    pets: 'none', kids: 'not_sure', goal: 'long_term_open',
    bio: 'I make ads and short documentaries. Always looking for the next good story and the next good nasi kandar.',
    tags: ['photography', 'concerts', 'documentaries', 'coffee', 'edm'],
    pr: [
      ['perfect_first_date', 'A night market walk in Taman Connaught, both of us with a 10 ringgit budget.'],
      ['weirdly_good_at', 'Finding golden hour on any street in KL.'],
      ['karaoke_song', 'Bunkface, Situasi. Loud and with full emotion.'],
    ],
  },
  {
    n: 'Rahul Menon', u: 'rahul.menon', g: 'male', a: 26, c: 'SJ', job: 'Houseman doctor',
    edu: 'bachelor', h: 175, rel: 'hinduism', lang: ['english', 'malay', 'tamil', 'hindi'], dr: 'sometimes', sm: 'never',
    pets: 'none', kids: 'want', goal: 'serious',
    bio: 'Houseman at a government hospital. When I am not on call I run, play badminton and watch Malayalam movies.',
    tags: ['running', 'badminton', 'bollywood', 'podcasts', 'cooking'],
    pr: [
      ['green_flags', 'You understand that "on call" means I really can not reply.'],
      ['way_to_heart', 'Banana leaf rice on my day off and someone who lets me sleep in.'],
      ['two_truths_lie', 'I have run a full marathon. I cook a great avial. I have never had a coffee.'],
    ],
  },
]

// Mutual likes between new fakes. With `chat`, the match gets these messages ([who, text], who 0
// is the first person, 1 the second), sent over the last few days.
export const MATCHES = [
  ['Amir Hamzah', 'Nurul Izzah', [
    [0, 'Hey! Roti telur bawang and teh o ais limau? That is a serious order'],
    [1, 'Haha it is the only correct order. Yours?'],
    [0, 'Roti canai kosong, kuah campur. Very basic I know'],
    [1, 'Basic but respectable. Which mamak do you go to?'],
    [0, 'The one near Kampung Baru LRT. You said you go there too right?'],
    [1, 'Yes!! Maybe we have seen each other already lol'],
    [0, 'Then this weekend we make it official. Saturday night?'],
    [1, 'Okay deal. I will be the one with the camera'],
  ]],
  ['Jason Teoh', 'Tan Hui Min', [
    [1, 'You said Musang King is overrated. Bold statement for a Penang boy'],
    [0, 'I stand by it. Black Thorn or nothing'],
    [1, 'Okay chef, then you have to prove it. Balik Pulau this Sunday?'],
    [0, 'Done. I will bring wet wipes, you bring the opinions'],
    [1, 'Haha deal. 9am before it gets too hot?'],
  ]],
  ['Kenneth Yong', 'Melissa Gimbang', [
    [0, 'A dive instructor in KK! Which site is your favourite?'],
    [1, 'Mantanani when the water is clear. You?'],
    [0, 'Hard to beat Sipadan but I am biased, I did my research there'],
    [1, 'Wah, marine biologist. So you can tell me the names of all the fish'],
    [0, 'Even the ugly ones. Tanjung Aru sunset and I tell you fish facts?'],
    [1, 'That is the nerdiest date offer I have ever had. Yes'],
  ]],
  ['Ryan Jalong', 'Jessica Jimbun', [
    [1, 'Your dog Bujang approves all dates? What is the process'],
    [0, 'He sniffs your shoes and then decides. Very strict'],
    [1, 'Haha okay I will wear my best shoes. Kolo mee first?'],
    [0, 'Kolo mee at Carpenter Street. Sunday 8am?'],
    [1, '8am on a Sunday?? You are lucky you are cute'],
  ]],
  ['Vikram Nair', 'Aishwarya Pillai', [
    [1, 'You run around the lake too? Morning or evening?'],
    [0, 'Morning, around 6:30. Before Cyberjaya wakes up'],
    [1, 'Same! I think I have overtaken you once haha'],
    [0, 'Impossible. Okay maybe possible. Run together on Saturday?'],
    [1, 'Only if biryani comes after. I read your prompt'],
    [0, 'Biryani is guaranteed'],
  ]],
  ['Tom Becker', 'Elena Petrova', [
    [0, 'Another expat learning Malay! What is your favourite word so far?'],
    [1, 'Tumpang. It sounds polite and cute at the same time'],
    [0, 'Mine is "boleh". Works for almost everything'],
    [1, 'Haha true. Do you climb at the gym in PJ?'],
    [0, 'Yes, most Tuesdays. Want to join this week?'],
    [1, 'Boleh!'],
  ]],
  ['Gurpreet Singh', 'Ong Pei Shan', []],
  ['Marcus Ho', 'Grace Lim', [
    [0, 'Pilot and flight attendant. This feels like a drama plot'],
    [1, 'Haha which airline? Please say not mine'],
    [0, 'Not yours, so no awkward briefings'],
    [1, 'Good. Brunch in SS15 when we are both on the ground?'],
  ]],
]

// Feed posts by the new fakes: [author, named, body, comments [[author, named, text]]].
export const POSTS_FULL = [
  ['Jason Teoh', true, 'Penang people, where do you take a date when it rains? Every plan I make gets rained out.', [
    ['Tan Hui Min', true, 'Hin Bus Depot and then dessert on Lebuh Chulia. Rain proof.'],
    ['Hannah Joseph', false, 'Gurney Paragon cinema. Classic for a reason.'],
  ]],
  ['Sarah Tiong', false, 'First time on an app like this. Matched with someone in Kuching and we already planned kolo mee on Saturday. Wish me luck!', [
    ['Jessica Jimbun', false, 'Good luck! Kolo mee dates are the best dates.'],
    ['Ryan Jalong', false, 'Order the red one. Trust me.'],
    ['Dayang Nur Ain', true, 'Update us after!'],
  ]],
  ['Elena Petrova', true, 'In KL for two years and still learning Malay. Tell me your favourite word that has no English translation.', [
    ['Nurul Izzah', true, 'Rindu. Missing someone, but deeper.'],
    ['Amir Hamzah', false, 'Geram. When something is so cute you want to squeeze it.'],
    ['Tom Becker', true, 'Paiseh. Wait, that one is Hokkien.'],
    ['Ong Pei Shan', false, 'Lepak. A whole lifestyle.'],
  ]],
  ['Harith Zulkifli', false, 'How long do you text before meeting? After a week it starts to feel awkward.', [
    ['Grace Lim', false, 'Three to five days for me. Enough to know you are not weird.'],
    ['Lim Wei Jie', false, 'Suggest a coffee in the first few days. Low pressure.'],
  ]],
  ['Ethan Goh', false, 'Unpopular opinion: durian on a first date is the ultimate compatibility test.', [
    ['Khairul Anwar', true, 'Agree. If she says no to durian, I respect it but I am sad.'],
    ['Puteri Balqis', false, 'Me, a durian hater, reading this in silence.'],
    ['Jason Teoh', true, 'Black Thorn or it does not count.'],
  ]],
  ['Melissa Gimbang', true, 'Sunset at Tanjung Aru today was unreal. Whoever matches with me, this is our first date spot.', [
    ['Kenneth Yong', true, 'Noted.'],
    ['Farhana Ismail', false, 'KK is on my list now, thank you.'],
  ]],
  ['Nur Syafiqah', false, 'Is it okay to say you are not ready for marriage talk on the third date? My family keeps asking lol', [
    ['Mira Hassan', true, 'Completely fine. Honesty early saves everyone time.'],
    ['Hafiz Azlan', false, 'Third date is too early for that anyway.'],
    ['Aishwarya Pillai', false, 'Tell your family the algorithm is still loading.'],
  ]],
  ['Vikram Nair', true, 'Cyberjaya folks, any running group on weekday mornings? Happy to start one if not.', [
    ['Aishwarya Pillai', true, 'Count me in. 6:30 at the lake?'],
    ['Arif Danial', false, 'I will join if it is after 9am. Students have rights.'],
  ]],
  ['Ethan Goh', false, 'JB to Singapore every day plus dating means my free time is 2 hours on Sunday. Anyone else?', [
    ['Hafiz Azlan', false, 'Find someone who also commutes, then you have 2 hours together in the jam.'],
  ]],
  ['Chong Li Wen', false, 'Prompt answers are so much better than bios. You learn more from someone\'s mamak order than a whole paragraph.', [
    ['Suresh Kumar', true, 'As a restaurant owner I approve this message.'],
    ['Nazrin Hakimi', false, 'Roti tisu people are the most fun, change my mind.'],
  ]],
]
