import {
  BadgeCheck,
  CheckCheck,
  Crown,
  Eye,
  EyeOff,
  Footprints,
  Heart,
  HeartHandshake,
  Image as ImageIcon,
  Link2,
  MessageCircleHeart,
  MessageSquareText,
  Mic,
  PenLine,
  Phone,
  Rocket,
  Sparkles,
  ThumbsUp,
  Ticket,
  Users,
  Video,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { FeatureKey } from '../access'

// One icon per matrix key (upgrade sheet header, comparison rows).
export const FEATURE_ICONS: Record<FeatureKey, LucideIcon> = {
  likes_per_day: Heart,
  who_liked_you: HeartHandshake,
  chat_photos: ImageIcon,
  voice_messages: Mic,
  video_messages: Video,
  calls: Phone,
  feed_post: PenLine,
  feed_comment: MessageSquareText,
  feed_like: ThumbsUp,
  blind_dating_per_day: Sparkles,
  event_priority: Ticket,
  incognito: EyeOff,
  boost: Rocket,
  crush_links_per_30d: Link2,
  duo: Users,
  statuses: Zap,
  crossed_paths: Footprints,
  vip_badge: Crown,
  read_receipts: CheckCheck,
  profile_visitors: Eye,
  discover_priority: BadgeCheck,
  message_before_match: MessageCircleHeart,
}
