// Russian labels of moderation_actions.action (journal page and CSV export). Unknown actions are
// shown as is, so a new action never breaks the journal.
export const ACTION_LABELS: Record<string, string> = {
  'verification.approve': 'Одобрил селфи',
  'verification.reject': 'Отклонил селфи',
  'user.ban': 'Заблокировал бессрочно',
  'user.temp_ban': 'Заблокировал временно',
  'user.unban': 'Разблокировал',
  'auto.unban': 'Автоснятие: срок блокировки истёк',
  'user.revoke_verification': 'Снял верификацию',
  'user.warn': 'Вынес предупреждение',
  'warning.revoke': 'Отменил предупреждение',
  'user.mute': 'Выдал мут',
  'user.unmute': 'Снял мут',
  'user.shadow_ban': 'Включил теневой бан',
  'user.shadow_unban': 'Выключил теневой бан',
  'user.evidence_hold': 'Включил удержание данных',
  'user.evidence_release': 'Снял удержание данных',
  'post.hide': 'Скрыл пост',
  'post.unhide': 'Вернул пост',
  'comment.hide': 'Скрыл комментарий',
  'comment.unhide': 'Вернул комментарий',
  'reports.resolve': 'Закрыл жалобы',
  'photo.delete': 'Удалил фото',
  'auto.hide': 'Автоскрытие: 3+ жалобы',
  'call.recording_open': 'Открыл запись звонка',
  'appeal.accept': 'Принял апелляцию',
  'appeal.reject': 'Отклонил апелляцию',
  'note.add': 'Добавил заметку',
  'note.delete': 'Удалил заметку',
  'phone.block': 'Заблокировал номер',
  'prompt.add': 'Добавил вопрос дня',
  'prompt.edit': 'Изменил вопрос дня',
  'prompt.move': 'Переставил вопрос дня',
  'prompt.delete': 'Удалил вопрос дня',
  'status.approve': 'Одобрил статус',
  'status.remove': 'Удалил статус',
  'phone.unblock': 'Разблокировал номер',
  'admin.add': 'Добавил в команду',
  'admin.role': 'Изменил роль',
  'admin.remove': 'Удалил из команды',
  'view.selfie': 'Просмотр селфи',
  'view.phone': 'Просмотр номера телефона',
  'view.transcript': 'Просмотр переписки блайнд-дейта',
  'export.audit_log': 'Выгрузил журнал (CSV)',
  'legal.export': 'Выгрузил данные по юр. запросу',
  'event.create': 'Создал вечер свиданий вслепую',
  'event.update': 'Изменил вечер свиданий вслепую',
  'event.cancel': 'Отменил вечер свиданий вслепую',
  'promo.create': 'Создал промокод',
  'promo.update': 'Изменил промокод',
  'promo.activate': 'Включил промокод',
  'promo.deactivate': 'Выключил промокод',
  'plan.feature': 'Изменил функцию плана',
  'plan.limit': 'Изменил лимит плана',
  'plan.grant': 'Выдал план',
  'plan.revoke': 'Отозвал план',
  'evidence.transcript_open': 'Открыл переписку по жалобе',
  'evidence.media_open': 'Открыл медиафайл по жалобе',
  'duo_bio.approve': 'Одобрил описание дуо',
  'duo_bio.reject': 'Отклонил описание дуо',
}

export const actionLabel = (action: string) => ACTION_LABELS[action] ?? action
